### ISSUE TITLE
Ошибка платежа

### ISSUE THREAD

**Issue by Dartrisen** [mostm/pyqiwi#24]
Пытаюсь перевести деньги со счета на счет
`def send_to_user(self, recipient, amount):
    payment = self.wallet.qiwi_transfer(recipient, amount, comment=None)`
однако, получаю странную ошибку:

> Traceback (most recent call last):
  File "pay.py", line 70, in <module>
    qp.send_to_user(recipient=phone, amount=1.0)
  File "pay.py", line 56, in send_to_user
    payment = self.wallet.qiwi_transfer(recipient, amount, comment=None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqiwi/__init__.py", line 393, in qiwi_transfer
    return self.send("99", account, amount, comment=comment)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqiwi/__init__.py", line 282, in send
    result_json = apihelper.payments(self.token, pid, amount, recipient, comment=comment, fields=fields)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqiwi/apihelper.py", line 161, in payments
    return _make_request(token, api_method, method='post', json=body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqiwi/apihelper.py", line 48, in _make_request
    return _check_result(method_name, result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqiwi/apihelper.py", line 59, in _check_result
    raise exceptions.APIError(msg, method_name, response=result)
pyqiwi.exceptions.APIError: ('The server returned HTTP 400 Bad Request. Response body:\n[b\'{"code":"QWPRC-319","message":"\\xd0\\x9f\\xd0\\xbb\\xd0\\xb0\\xd1\\x82\\xd0\\xb5\\xd0\\xb6 \\xd0\\xbd\\xd0\\xb5\\xd0\\xb2\\xd0\\xbe\\xd0\\xb7\\xd0\\xbc\\xd0\\xbe\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd "}\']', 'payments')

сам сайт киви видит мои транзакции, но пишет что произошла ошибка платежа

**Comment by Dartrisen** [comment]
Все разрешилось. Нельзя послать деньги самому себе.
